name: Cron actions

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  hassfest:
    name: Hassfest validation
    runs-on: "ubuntu-latest"
    steps:
        - name: Check out the repository
          uses: "actions/checkout@v2"
        - name: Hassfest validation
          uses: "home-assistant/actions/hassfest@master"

  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"